if(NOT DEFINED ENV{AARCH64_TOOLCHAIN_PREFIX} OR "$ENV{AARCH64_TOOLCHAIN_PREFIX}" STREQUAL "")
  message(FATAL_ERROR "AARCH64_TOOLCHAIN_PREFIX must name the cross-compiler prefix")
endif()

if(NOT DEFINED ENV{AARCH64_SYSROOT} OR "$ENV{AARCH64_SYSROOT}" STREQUAL "")
  message(FATAL_ERROR "AARCH64_SYSROOT must name the target sysroot")
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER "$ENV{AARCH64_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "$ENV{AARCH64_TOOLCHAIN_PREFIX}g++")
set(CMAKE_SYSROOT "$ENV{AARCH64_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "$ENV{AARCH64_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
